### ISSUE TITLE
这么好的东西不发表出去可惜了

### ISSUE THREAD

**Issue by vagrant-soul** [meethigher/black-wukong-youji#1]
建议直接发到网上，这个地方受众还是小

**Comment by meethigher** [comment]
感谢建议



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月27日(星期二) 中午11:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [meethigher/black-wukong-youji] 这么好的东西不发表出去可惜了 (Issue #1)














 
建议直接发到网上，这个地方受众还是小

**Comment by Mapaler** [comment]
本来想加入工作，结果发现wiki上早就整理好了
https://wiki.biligame.com/wukong/%E6%95%8C%E4%BA%BA

**Comment by meethigher** [comment]
> 本来想加入工作，结果发现wiki上早就整理好了 https://wiki.biligame.com/wukong/%E6%95%8C%E4%BA%BA

非常可以！！我本来就是想整理个这东西，可惜当时没找到。

**Comment by ChosenXu** [comment]
这一套内容真的不错，期待游科在未来可以出实体书

**Comment by meethigher** [comment]
> 这一套内容真的不错，期待游科在未来可以出实体书

是的。游戏通关之后，剧情给我的感觉是一般，说他是西游记的延续有点勉强了，不如说是斗战神的延续。

但是这里面的妖怪游记，是真的特别惊艳。
