### ISSUE TITLE
Wiki网站已经有所有文本和图像，有何必要拷贝过来重制一份呢？

### ISSUE THREAD

**Issue by Leegenux** [meethigher/black-wukong-youji#3]

**Comment by meethigher** [comment]
游科自己能出个周边最好了，当时没找到，因此才花费了大力气整理的。而且wiki是在我整理了时才得知的。之前都是文本识别。

下面回答你的问题。
首先，排版和错别字其实经过了处理了，我相当于是边读边整理。甚至游戏里面都有错别字的问题。我处理过了。这也就回答了你觉得是拷贝复制的问题。但是目前比较严重的是标点符号问题，尤其是中文引号。虽然我处理过了，不过可能还有疏漏。
其实更主要的，是因为想要做所以做，这一点情怀部分更多，大多数人应该不理解。所以我一直提同道中人。

**Comment by nile52** [comment]
1.9 鸦香客，说自己的**鸟鸦**正是庙中通灵的老鸦。

**Comment by meethigher** [comment]
感谢指出，周末我再改改
