### ISSUE TITLE
「勘误」1.13 小菌君

### ISSUE THREAD

**Issue by ebnOs0** [meethigher/black-wukong-youji#4]
原：空中又散出许多菌丝飞射到众人的身。上，
改：空中又散出许多菌丝飞射到众人的身上，

**Comment by meethigher** [comment]
> 原：空中又散出许多菌丝飞射到众人的身。上， 改：空中又散出许多菌丝飞射到众人的身上，

已更正。有兴趣的话可以拉个pull request。

**Comment by ebnOs0** [comment]
好的，之后有新的发现我提pr，感谢搬运
